apiVersion: 1

datasources:
  - name: MySQL
    uid: mysql-airflow
    type: mysql
    access: proxy
    isDefault: true
    editable: true
    url: mysql:3306
    user: ${MYSQL_USER}
    jsonData:
      database: ${MYSQL_DB}
      maxOpenConns: 25
      maxIdleConns: 25
      connMaxLifetime: 14400
      tlsAuth: false
    secureJsonData:
      password: ${MYSQL_PASSWORD}
