name: Airflow CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to GCP VM
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VM_HOST }}
                  username: ${{ secrets.VM_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd Build-Data-Pipeline-using-Apache-Arirflow
                      git pull

                      # create necessary directories and set permissions for Airflow
                      sudo mkdir -p dags logs data scripts
                      sudo chown -R 50000:0 dags logs data scripts

                      docker compose down
                      # Rebuild and start the containers. If it fails, show logs for debugging.
                      docker compose up -d --build || (docker logs airflow-init && exit 1)
